options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 1
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 1
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-protocols: 1
  no-vendor-prefixes:
    - 2
    -
      ignore-non-standard: true
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format: 0
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 2
  brace-style:
    - 2
    -
      style: '1tbs'
      allow-single-line: false
  clean-import-paths: 2
  empty-args:
    - 1
    -
      include: false
  hex-length:
    - 2
    -
      style: 'long'
  hex-notation:
    - 2
    -
      style: 'uppercase'
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: true
  nesting-depth: 0
  property-sort-order:
    - 2
    -
      order: 'smacss'
      ignore-custom-properties: true
  pseudo-element: 2
  quotes:
    - 2
    -
      style: 'single'
  shorthand-values: 0
  url-quotes: 2
  variable-for-property: 0
  zero-unit:
    - 2
    -
      include: false

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 1
